mozilla/python_moztelemetry

moztelemetry/heka_message_parser.py

Not all of the payload is pulled out into separate fields, so the
base object should start with the protobuf "payload" field. See
https://github.com/mozilla-services/data-pipeline/blob/master/heka/sandbox/decoders/extract_telemetry_dimensions.lua#L168-L169
For what is currently pulled out into separate fields.
Also, introduce a "meta" section to hold the top-level message fields,
such as Timestamp and Type, as well as the fields that are not part
of the original incoming payload (such as geoCountry, sampleId, DNT).

Add Heka fields to a "meta" section, add payload.

---

moztelemetry/histogram.py
moztelemetry/spark.py

This is needed because we occasionally need to use histograms that have
been deleted from the mozilla-central Histograms.json.

Allow Histograms.json URL to be specified with get_pings_properties

---

moztelemetry/histogram.py
moztelemetry/spark.py

Tested by running Hello world analysis and a separate analysis that uses the `additional_histograms` parameter.

Add additional_histograms parameter to support arbitrary histograms

---

moztelemetry/spark.py

It is convient to be able to rename the property keys in the output of get_pings_properties rather than using the full original paths. 
The functionality for separating the property names in the results from the paths is already there, and this change exposes it via the API.

Allow custom keys in output of get_pings_properties

---

moztelemetry/standards.py

Ideally this will be extended to include other common assumptions
and computed measures. For now, add MAU and DAU per bug 1240849.

Introduce a new 'standards' library

---

moztelemetry/filter_service.py
moztelemetry/spark.py

Add host argument to connect_s3 calls

---

moztelemetry/filter_service.py
setup.py

@vitillo or @mreid this is going to need to be pushed to pypi again

Fix syntax and bump version

---

README.md
moztelemetry/standards.py
setup.py
tests/test_dates.py

As suggested by @mreid-moz , I'm adding these utility functions which are being used by the Fennec dashboard.
Where should I write test coverage (if that's needed in this case)?

Added get_last_{week|month}_range and snap_to_beginning_of_{week|month].

---

LICENSE
README.md

* assuming the MPL license is ok, it might not be, so please let me know
* also no note about how to install, so I added the pip command
* fixes #65

add license and how to install

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/71)

Add travis status image to README.md

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/70)

Add coveralls status image to README.md

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/73)

Bug 1288086 - Run coveralls on CI

---

moztelemetry/spark.py

When bug 1218576 lands, Firefox will start sending child histograms in
<payloadRoot>.processes.child.{keyedH|h}istograms
instead of
<payloadRoot>.childPayloads[i].{keyedH|h}istograms
Handle pings that have child histograms in either (or a mix of both) config.
Tested that current-format pings' child data is available via get_pings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/72)

Bug 1286951 - Allow child histograms to be in processes.content as well as childPayloads[i]

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/75)

Bug 1286951 - Bump version for child telemetry changes

---

moztelemetry/spark.py
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/74)

Bug 1251631 - remove getpings v2

---

moztelemetry/dataset.py
tests/test_dataset.py

This is needed to have feature parity with get_pings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/77)

Bug 1292111 - Add sample parameter to Dataset.records

---

.travis.yml
docs/userguide.rst
environment.yml
readthedocs.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/79)

Bug 1294663 - fix use of autodoc on readthedocs

---

moztelemetry/dataset.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/84)

Bug 1307460 - Fix typo in usage example

---

moztelemetry/histogram.py
moztelemetry/histogram_tools.py
setup.py
tests/test_histogram.py

@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/85)

Bug 1305757 - Categorical histo support

---

moztelemetry/dataset.py
moztelemetry/spark.py
setup.py
tests/test_spark.py

This is using partial functions to store the correct range filter
values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/87)

Bug 1315243 - fix  multiple range filters in get_pings

---

moztelemetry/dataset.py
setup.py
tests/test_dataset.py

This is using a partial function to store the filter value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/89)

Bug 1317784 - Dataset.where should accept multiple parameters

---

moztelemetry/dataset.py

@maurodoglio r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/90)

Bug 1291723 - Make the dataset docs run

---

moztelemetry/dataset.py
setup.py
tests/test_dataset.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/91)

Bug 1318296 - Add `summaries` parameter  to Dataset.records()

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/92)

Bug 1318703 - Use setuptools_scm to define package version

---

moztelemetry/hbase.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/96)

Find HBase master using tags.

---

moztelemetry/hbase.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/98)

Fix documentation of HBaseMainSummaryView.

---

moztelemetry/hbase.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/99)

Improve documentation of HBaseMainSummaryView.

---

moztelemetry/histogram.py
tests/test_histogram.py

@vitillo r? Or @maurodoglio if you're the module owner? Not totally sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/102)

Bug 1330500 - Fix dict instances with categorical histograms

---

moztelemetry/hbase.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/106)

Fix documentation typos.

---

moztelemetry/scalar.py
setup.py
tests/Scalars.yaml
tests/test_scalar.py

This mirrors, somewhat, the histogram class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/103)

Bug 1297080 - Add scalar support

---

moztelemetry/spark.py
setup.cfg

Hey @fbertsch do you mind to take a look at this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/105)

Code cleanup

---

moztelemetry/spark.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/104)

Bug 1331005 - Support GPU process histograms/keyedHistograms in get_pings_properties

---

moztelemetry/dataset.py
tests/test_dataset.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/108)

Bug 1322768 - Use Spark to list file summaries

---

moztelemetry/dataset.py

Calling Dataset.where only once results in more readable code.

Update Dataset.where docs

---

setup.py

Since we are just a library that others include

Specify happybase as a >= dependency, not a == dependency

---

docs/api.rst
docs/index.rst

Make sure the `API` section expands correct in the sidebar

Very minor doc tweaks

---

moztelemetry/histogram_tools.py

This ought to do it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/153)

bug 1364556 - update histogram_tools to latest m-c version.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/158)

Add info about the update process in the README

---

moztelemetry/spark.py
tests/test_spark.py

Bug 1397955 - get_pings_properties: Handle boolean scalars with false values

---

moztelemetry/dataset.py

Fixes Bug 1414582 Print a warning when using the "sample" functionality of Dataset
r? @mreid-moz

Bug 1414582 - Print warning for "sample"

---

.gitignore
.travis.yml
Dockerfile
README.md
environment.yml
moztelemetry/__init__.py
moztelemetry/dataset.py
moztelemetry/heka/message_parser.py
moztelemetry/histogram.py
moztelemetry/parse_histograms.py
moztelemetry/parse_scalars.py
moztelemetry/scalar.py
moztelemetry/shared_telemetry_utils.py
moztelemetry/spark.py
moztelemetry/store.py
moztelemetry/util/streaming_gzip.py
runtests.sh
setup.py
tests/heka/test_message_parser.py
tests/test_dataset.py
tests/test_spark.py
tests/test_standards.py
tests/test_store.py

and make python3 default in docker

Add support for python3

---

moztelemetry/dataset.py
tests/test_dataset.py

It's unclear how to add a new test where objects are being added to the mock-store. In particular, using `json.load` as the decode function in `Dataset.records` has strange behavior because records can be concatenated when they're stored to disk. 
In  `test_dataset`, the helper function is moved to the top of the file and a new test case is added. I also rewrote the `Dataset.records` function so that it's possible to step line-by-line in pdb.

Reorganize `Dataset.record` for clarity

---

moztelemetry/standards.py
setup.cfg

Per conversation on IRC, the current docstring is confusing.

Update docstring to clarify SparkContext vs. SparkSession

---

README.md
docs/index.rst

After this is merged, we can set the repo as archived.

Final deprecation/archive docs
