moztelemetry/heka_message_parser.py, moztelemetry/spark.py, setup.py
Add a `get_records` function that can be used to fetch (and filter) data for derived streams using the Pipeline metadata.
=> Derived streams

moztelemetry/spark.py
We don't want to default to "allowed_values" = null, so we skip
un-set field filters. This means you don't have to specify a value
for every available field.
=> Skip null field filters.

moztelemetry/heka_message_parser.py, setup.py
Temporary workaround for problems caused by "bytes" fields (in the Telemetry case, it is the `submission` field containing gzipped bytes).
=> Skip bytes hackishly

moztelemetry/spark.py
The telemetry schema uses `"*"` as a wildcard, to mean "allow all values for that field". When this is passed to `get_pings` it should be interpreted as "match any value" but it is treated as "match the string `'*'`".
This can be fixed by replacing `"*"` with `None` right before calling `SDB.query`.
=> Handle case of passing "*" as an arg to get_pings()

moztelemetry/spark.py
If one of the paths passed to `get_pings_properties` points to the name of a keyedHistogram without including an actual key, return a dict containing subhistograms for all available keys for that keyedHistogram.
As far as I can tell, the only thing this could potentially break is if something depends on catching the error thrown at https://github.com/mozilla/python_moztelemetry/blob/master/moztelemetry/spark.py#L484, although I'm guessing this would be unlikely.
=> Make get_pings_properties return all subhistograms for a keyedHistogram with missing key

moztelemetry/spark.py
Patch for PR #46.
Sorry - rookie mistake. I forgot to handle the case missing keyedHistogram name. This showed up in use on a larger dataset.
=> Fix for _get_pings_properties for subhistograms

moztelemetry/standards.py
Convert a number (or numeric string) containing a number of days
since Jan 1, 1970 to a date.
Incidentally, also fix a line-break problem.
=> Add a standard function for converting day number to a date.

moztelemetry/histogram.py, moztelemetry/spark.py
When keyed histograms have keys in the child that don't exist in the parent, `get_ping_properties` doesn't return those keys.
Keys in keyed histograms in the child payloads are only returned if the keyed histogram in the parent process has those keys as well.
Here's a sample with the new hello world notebook: https://gist.github.com/Uberi/7d607a6035116f2f8c09. The second half was taking really long, so I interrupted it after running all the code that can call or indirectly access `_get_ping_properties` and `_get_merged_histograms`.
=> Fix retrieving keyed histograms missing keys

moztelemetry/filter_service.py, moztelemetry/spark.py
Calling `get_pings` in a loop will eventually (around 100 for the default hadoop setup) make us run out of threads.
This is because the threadpool for SDB shuts down asynchronously, so the number of threadpools keeps growing.
To solve this, we can make thread pool shutdown synchronous (to make the class behave correctly), and also cache the SDB instances (to make things fast again). We can cache these instances because they don't have any real mutable state.
Here's a notebook that demonstrates a loop that uses only one thread pool at a time: https://gist.github.com/Uberi/9e2315e152b35595e917
=> Fix threading issue with SimpleDB

moztelemetry/heka_message_parser.py, moztelemetry/spark.py, setup.py
This is a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1248845.
Chunking was introduced to reduce the memory pressure. Since then
some configuration changes have landed that deal with the issue
in a more general way so that chunking should be no longer required.
=> Remove Heka file chunking.

.travis.yml, README.md, bin/update_histogram_tools, moztelemetry/histogram.py, moztelemetry/histogram_tools.py, setup.cfg, setup.py, tests/test_histogram.py
This adds a basic setup to run tests using [pytest](http://pytest.org).
It also adds histogram_tools.py to this repository, so from now on we need to bump up the minor version of this library everytime that file is updated on mozilla-central.
=> Setup tests

moztelemetry/dataset.py, setup.py, tests/test_dataset.py
If there are no conditions left to check, _scan should return the list
of prefixes retrieved up to the point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/80)
=> Bug 1302476 - Make Dataset._scan return early

moztelemetry/dataset.py, setup.py, tests/conftest.py, tests/test_dataset.py
For most of the datasets grouping the source files by cumulative size
works well. For datasets with many small files, there may be cases where
the size threshold is never/hardly reached and all the files end up being in
a number of groups < defaultParallelism. Let's ignore the grouping in
those case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/81)
=> Bug 1304693 - Better handle datasets with many small files

moztelemetry/dataset.py, setup.py
The filtered dataset shouldn't be returned on the first iteration but after the
for loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/83)
=> Fix Dataset.where with multiple filters

moztelemetry/dataset.py
Similar to https://github.com/mozilla/python_moztelemetry/blob/master/moztelemetry/spark.py#L277
This value of `metadata_prefix` is usually (but not always) the same as `prefix`, which is why it has worked so far. The case where it's not is when you have two datasets with the same metadata prefix, as occasioned by forthcoming dataset migrations. 
We should produce better documentation and tooling around `sources.json` in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/86)
=> Bug 1302264 - Use metadata_prefix in the Dataset API

docs/userguide.rst, moztelemetry/zeppelin.py
Zeppelin doesn't currently support Matplotlib out of the box so this is the only way to display a plot.
=> Add Zeppelin plotting helper

moztelemetry/dataset.py, tests/test_dataset.py
The idea here is to use a greedy algorithm to balance the RDD partition
in terms of number of files (first) and total size of each partition.
=> Bug 1349608 - Improve Dataset handling of small pings

tests/test_hbase.py
If you interrupt the hbase unit tests when they're running, that can leave
a table in a disabled-but-not-deleted state which the current fixture
can't handle correctly. Let's account for this case.
=> Fix hbase test fixtures when tests interrupted

setup.py
Also remove the deprecated use of dependency_links in the setup file
(which didn't work without a special command-line option).
=> Bug 1353032 - Depend on happybase 1.1.0

moztelemetry/dataset.py, tests/test_dataset.py
So this seems almost too easy, but the unit tests (including a new one which would stress test whether this case is working correctly) are still passing. From what I can tell, when a prefix is specified we have a filter to make sure the data we fetch from S3 matches the prefix. This doesn't work well when our prefix has slashes in it (because it depends on being able to work against the last part of the path). However, I don't see why this is even necessary because we explicitly only get data matching the prefix from S3 (https://github.com/mozilla/python_moztelemetry/blob/06d26e6/moztelemetry/dataset.py#L128)
@mreid-moz @maurodoglio Could you tell me if I'm crazy?
=> Bug 1346308 - Support dataset prefixes with slashes

moztelemetry/dataset.py, tests/test_dataset.py
We need to pass in a dimension corresponding to the prefix so that we actually
scan in the appropriate folder, even if we don't actually need a clause that
filters *for* the prefix (since that is taken care of by our interaction with
the S3 API).
=> Bug 1346308 - Fix using where() on a dataset when prefix specified

Dockerfile, runtests.sh
This patch fixes a few problems with the docker test setup:
- Conda virtual environment activation
- runtest.sh execution with no arguments
- Huge speedup on subsequent builds of the docker container.
=> Minor fixes to the test environment

moztelemetry/histogram.py, moztelemetry/histogram_tools.py, moztelemetry/shared_telemetry_utils.py, setup.cfg, tests/test_histogram.py
It's been a while since moztelemetry's copy of histogram_tools was updated so
there are two things that need to be addressed.
1) We need to handle that Categorical histograms have a default of 50 n_buckets
So truncate values as moztelemetry.Histograms are constructed
2) record_in_processes is required in histogram definitions
So use more recent versions of histogram definitions that comply
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/151)
=> Bug 1363934 - Update moztelemetry's ages-old histogram_tools, fixing tests.

moztelemetry/spark.py, tests/test_spark.py
[Bug 1318326 - |get_pings_properties| does not return all the available keyedHistograms](https://bugzilla.mozilla.org/show_bug.cgi?id=1318326)
This PR introduces failing tests that demonstrate the current behavior of `get_pings_properties` when retrieving keyedHistograms in pings that contain child processes. This is solved by defaulting to empty dictionaries to avoid `KeyError` exceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_moztelemetry/150)
=> Bug 1318326 - Fix `get_pings_properties` for keyedHistograms

moztelemetry/heka/message_parser.py, tests/heka/test_message_parser.py
This has potential performance implications. We should do some testing to see how it performs when we just parse all the json.
=> Bug 1376028 - Stop using Lazy json evaluation

README.md
The procedure has changed slightly, see the following:
https://packaging.python.org/guides/migrating-to-pypi-org/#uploading
=> Update instructions for publishing to PyPI

moztelemetry/scalar.py, tests/test_scalar.py
We are guaranteed that no two scalars in scalars.yaml will share
a case-insensitive name. Currently, the Scalar class fails to
return a scalar when given a proper scalar name that is not
cased correctly. This change matches any case.
=> Bug 1380438 - Make scalar names case-insensitive

.gitignore, Dockerfile, environment.yml, moztelemetry/stats.py, setup.py, tests/test_stats.py
=> Add Mann-Whitney U test methods (bug 1395571)

Dockerfile, README.md, runtests.sh
Coveralls is currently making it impossible to merge PRs, since
they are not having the coveralls status reported. Admins also
cannot override this.
=> Remove Coveralls

tests/heka/test_message_parser.py
There doesn't seem to be a test for nested fields names like "foo.bar.baz". This tests the recursive behavior of flattened fields that are nested several levels.
=> Add test for extracted fields that are nested

Dockerfile, moztelemetry/standards.py
> this would be most useful if we want to sample down from a dataframe already filtered by sample_id, so we may want to detect the first non-empty modulo result
as long as we re-use the sample_id we filter by (optionally plus multiples of 100), and modulo is a multiple of 100, then that use case is covered.
=> Bug 1445774 - Port client sampling to python

moztelemetry/heka/message_parser.py, tests/heka/test_message_parser.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1447851)
Option b seemed like a good choice. Landfill messages will be parsed directly into a string, which can be later decoded using `json.loads` if needed.
=>  Bug 1447851 - Add content decoding for landfill

moztelemetry/dataset.py, tests/test_dataset.py
Could I get some feedback on these changes? This method groups files into equally sized groups, as an alternative to the greedy strategy.
The method passes the unit tests. Next step is to test it against the benchmark tests after it is included.
=> Bug 1463877 - partition strategy

setup.cfg
After tagging and watching this project appear on PyPI, I noticed that the produced wheel distribution is python 3 only:
https://pypi.org/project/python_moztelemetry/0.10.1/#files
But this project natively supports 2 and 3, so we should upload a universal wheel.
=> Deploy a universal wheel for both Python 2 and Python 3

.dockerignore, README.md, bin/clean, bin/test, tox.ini
This should avoid the problem of files being created with root ownership on Linux hosts.
=> Use a named docker volume for tox cache

tox.ini
`./bin/test tests/heka/` was running all tests rather than just those in the
target directory because `--cov` was eating the directory, assuming it was
the argument of where we should do code coverage.
=> Pass expected argument to --cov

.circleci/config.yml, README.md, docs/conf.py, docs/requirements.txt, readthedocs.yml, tox.ini
We should definitely be testing docs as part of CI to make sure they build,
which is addressed here. But this change also explores what it could look
like to publish docs to Github Pages rather than ReadTheDocs, so that we can
avoid the additional developer friction of understanding that service and
maintaining user permissions there.
The gh-pages docs are live at:
http://mozilla.github.io/python_moztelemetry/
A few features I notice missing that ReadTheDocs provides:
- hosting multiple versions of the docs, though we don't look to be using this
- download links for PDF, HTML, and Epub
- "Edit on GitHub" links; the gh-pages rendered version links to the content
on the gh-pages branch rather than on master
The above features are indeed nice to have. RTD is also a fairly python-specific …
=> Test docs and deploy to gh-pages branch

.circleci/config.yml, tox.ini
Just a few more changes to fix observed problems with docs and CI
=> gh-pages fixes

moztelemetry/dataset.py
Dataset.summaries uses a concurrent.futures.ProcessPoolExecutor to fetch multiple files from S3 at once.
ProcessPoolExecutor uses multiprocessing underneath, which defaults to using fork() on Unix.
Using fork() is dangerous and prone to deadlocks: https://codewithoutrules.com/2018/09/04/python-multiprocessing/
This is a possible source of observed deadlocks during calls to Dataset.records.
Using threads should not be a performance regression since the operation we're parallelizing over is network-bound,
not CPU-bound, so there should not be much contention for the GIL.
=> Use threads instead of processes in Dataset.summaries

moztelemetry/dataset.py
Explain that replacing `key="a-value"` with `key=lambda x: x
in ("a-value", "b-value")` will not work.
=> Document that callables receive sanitized values
